packages/wallet/src/ui/Input.tsx, packages/wallet/src/ui/Label.tsx
- Add a basic `Input` component
- Simple `Label` component
=> feat(wallet): add input component

packages/wallet/package.json, packages/wallet/src/pages/_document.tsx, packages/wallet/src/ui/ButtonOrLink.tsx, packages/wallet/src/ui/FieldError.tsx, packages/wallet/src/ui/Form.tsx, packages/wallet/src/ui/Input.tsx, packages/wallet/src/ui/Label.tsx, pnpm-lock.yaml
Add reusable `Form` component.
---
**Edit:**
<details>
<summary>Form preview</summary>
</details>
=> feat(wallet): add form component

.github/labeler.yml, .github/workflows/pr-labeler.yml
This workflow will automatically add labels to pull requests based on the configuration file.
https://github.com/interledger/testnet/blob/235bf5c747d79b3b6c1d4af852b75733e58f3691/.github/labeler.yml#L1-L17
=> feat(ci): add pr labeler

packages/wallet/src/components/layouts/AuthLayout.tsx, packages/wallet/src/pages/welcome.tsx, packages/wallet/src/ui/Button.tsx
Creates Welcome page as per requirement in story #16 
- creates welcome page /welcome
- changes the default button so it is not square like
- changes the auth layout so that desktop version stays longer in view (desktop version in main/priority)
=> feat(wallet): create welcome page

packages/wallet/src/pages/login.tsx, packages/wallet/src/ui/Input.tsx, packages/wallet/src/ui/Label.tsx
- fixes #53 
Implemented floating labels for inputs in forms
=> feat(wallet): implement floating label for form inputs

packages/wallet/src/pages/404.tsx, packages/wallet/src/pages/transfer/request.tsx
- fixes #22 
Added Request page for Transfers part
=> feat(wallet): Add Request Page

packages/wallet/src/components/Menu.tsx
=> feat(wallet): update desktop menu

docker/dev/docker-compose.yml
=> fix: escape characters for env variables

docker/dev/docker-compose.yml, packages/wallet/package.json, packages/wallet/src/lib/axios.ts, packages/wallet/src/utils/helpers.ts, pnpm-lock.yaml
=> feat(wallet): setup axios

pnpm-lock.yaml
- fixes #
Update rafiki to latest commit in main
=> chore: update rafiki

docker/dev/docker-compose.yml, package.json, packages/wallet/next.config.js, packages/wallet/package.json, packages/wallet/src/pages/index.tsx
- closes #162 
Since the application was in Docker, when trying to fetch a resource on the server the backend URL had to be `http://testnet` instead of `http://localhost`
=> chore: move next app outside docker

packages/wallet/src/components/PageHeader.tsx, packages/wallet/src/components/icons/Arrow.tsx, packages/wallet/src/pages/account/[accountId].tsx, packages/wallet/src/pages/account/[accountId]/[paymentPointerId].tsx, packages/wallet/src/pages/index.tsx, packages/wallet/src/pages/transfer/pay.tsx, packages/wallet/src/pages/transfer/request.tsx, packages/wallet/src/pages/transfer/send.tsx, packages/wallet/src/ui/Badge.tsx, packages/wallet/src/ui/Table.tsx
- closes #37
- Add transactions table for a payment pointer
=> feat(wallet): add transactions page

packages/wallet/package.json, packages/wallet/src/pages/_app.tsx, pnpm-lock.yaml
=> chore(wallet): remove `@next/font` dependency

packages/backend/src/index.ts, packages/backend/src/wallet/schemas/kycSchema.ts, packages/backend/src/wallet/wallet.service.ts, packages/wallet/src/components/kyc/VerifyIdentityForm.tsx, packages/wallet/src/lib/api/user.ts, packages/wallet/src/ui/forms/FileUpload.tsx, packages/wallet/src/utils/helpers.ts
- fixes #178 
Convert uploaded images to base64 and send them to verify identity
=> feat(wallet): KYC Verify Identity image uploads to base64

packages/backend/src/auth/auth.service.ts, packages/backend/src/auth/jwtStrategy.ts, packages/backend/src/wallet/wallet.service.ts
some hot fixes on create wallet api
=> feat(backend): returning new access token after wallet is created

packages/wallet/src/components/kyc/VerifyIdentityForm.tsx, packages/wallet/src/lib/api/user.ts, packages/wallet/src/utils/constants.ts
=> fix(wallet): Verify image type for KYC upload

packages/backend/src/account/account.service.ts, packages/wallet/src/components/AccountCard.tsx, packages/wallet/src/components/dialogs/FundAccountDialog.tsx, packages/wallet/src/lib/api/account.ts, packages/wallet/src/lib/api/asset.ts, packages/wallet/src/pages/account/create.tsx, packages/wallet/src/pages/index.tsx
=> feat(wallet): add list/create account

packages/wallet/src/components/dialogs/CreatePaymentPointerDialog.tsx, packages/wallet/src/components/dialogs/FundAccountDialog.tsx, packages/wallet/src/components/icons/Play.tsx, packages/wallet/src/components/icons/Spinner.tsx, packages/wallet/src/components/kyc/PersonalDetailsForm.tsx, packages/wallet/src/components/kyc/VerifyIdentityForm.tsx, packages/wallet/src/pages/account/create.tsx, packages/wallet/src/pages/auth/login.tsx, packages/wallet/src/pages/auth/signup.tsx, packages/wallet/src/pages/transfer/pay.tsx, packages/wallet/src/pages/transfer/request.tsx, packages/wallet/src/pages/transfer/send.tsx, packages/wallet/src/ui/Button.tsx
=> feat(wallet): Add loading state for buttons

packages/wallet/next.config.js, packages/wallet/src/components/Menu.tsx, packages/wallet/src/components/PaymentPointerCard.tsx, packages/wallet/src/components/dialogs/CreatePaymentPointerDialog.tsx, packages/wallet/src/lib/api/paymentPointer.ts, packages/wallet/src/middleware.ts, packages/wallet/src/pages/account/[accountId].tsx, packages/wallet/src/pages/account/[accountId]/[paymentPointerId].tsx, packages/wallet/src/utils/constants.ts, packages/wallet/src/utils/helpers.ts
=> feat(wallet): display transactions from database

packages/backend/src/incoming-payment/incoming-payment.service.ts, packages/backend/src/outgoing-payment/outgoing-payment.service.ts
=> fix(payment): create incoming payment on sent

packages/wallet/src/components/kyc/VerifyIdentityForm.tsx, packages/wallet/src/pages/account/[accountId].tsx, packages/wallet/tailwind.config.js
- fixes blue main color
- add payment pointer text size
- typo
=> feat(wallet): small design changes

packages/wallet-frontend/src/lib/api/transfers.ts, packages/wallet-frontend/src/pages/transfer/pay.tsx, packages/wallet-frontend/src/pages/transfer/send.tsx, packages/wallet-frontend/src/ui/TogglePayment.tsx
- fixes #261 
Correctly sends `isReceive: true | false` based on the sent/received toggle.
=> fix(wallet-frontend): sent/received toggle

.github/contributing.md, README.md
=> chore: update readme & contributing

docker/dev/docker-compose.yml
- fixes #308 
* Update Rafiki's docker images
* Update Tigerbeetle commit hash
=> chore: update Rafiki's tags and Tigerbeetle

packages/wallet-backend/migrations/20230209130752_transaction.js, packages/wallet-backend/src/middlewares/validator.ts, packages/wallet-backend/src/transaction/transaction.model.ts, packages/wallet-backend/src/transaction/transaction.schema.ts, packages/wallet-backend/src/transaction/transaction.service.ts, packages/wallet-frontend/src/pages/account/[accountId]/[paymentPointerId].tsx
=> feat(transactions): add default sort order by created at

.eslintrc.js, packages/wallet-frontend/src/lib/types/app.ts, packages/wallet-frontend/src/middleware.ts, packages/wallet-frontend/src/pages/_app.tsx, packages/wallet-frontend/src/pages/account/[accountId].tsx, packages/wallet-frontend/src/pages/account/[accountId]/[paymentPointerId].tsx, packages/wallet-frontend/src/pages/account/create.tsx, packages/wallet-frontend/src/pages/auth/index.tsx, packages/wallet-frontend/src/pages/auth/login.tsx, packages/wallet-frontend/src/pages/auth/signup.tsx, packages/wallet-frontend/src/pages/index.tsx, packages/wallet-frontend/src/pages/kyc.tsx, packages/wallet-frontend/src/pages/settings/api.tsx, packages/wallet-frontend/src/pages/settings/index.tsx, packages/wallet-frontend/src/pages/transfer/pay.tsx, packages/wallet-frontend/src/pages/transfer/request.tsx, packages/wallet-frontend/src/pages/transfer/send.tsx
- fixes #338 
- add per-page layouts
- taking advantage of React reconciliation (preventing layouts re-renders)
=> feat(wallet/frontend): add per-page layouts

packages/wallet-frontend/src/middleware.ts, packages/wallet-frontend/src/pages/transfer/send.tsx
=> fix(wallet): Bug fixes for KYC and PP Input

packages/wallet-frontend/src/components/kyc/VerifyIdentityForm.tsx
=> fix(wallet/frontend): redirect to homepage after kyc

packages/wallet-frontend/src/components/Menu.tsx, packages/wallet-frontend/src/components/settings/ApiKeys.tsx, packages/wallet-frontend/src/pages/auth/signup.tsx, packages/wallet-frontend/src/pages/index.tsx, packages/wallet-frontend/src/ui/CopyButton.tsx
=> fix(wallet-frontend): mobile bug fixes

packages/wallet-frontend/src/lib/api/transfers.ts, packages/wallet-frontend/src/pages/transfer/pay.tsx, packages/wallet-frontend/src/pages/transfer/send.tsx, packages/wallet-frontend/src/ui/TogglePayment.tsx, packages/wallet-frontend/src/utils/constants.ts
- fixes #361 
Added Toggle texts to constants, because if we need to change the text again, we need to do it in only 2 places and not 10+
=> feat(wallet-frontend): Text change for Switch

packages/wallet-backend/src/auth/auth.service.ts, packages/wallet-backend/src/config/env.ts
=> fix(wallet-backend): set correct cookie options

packages/wallet-backend-update/src/rapyd/controller.ts, packages/wallet-frontend/src/components/settings/PersonalSettingsForm.tsx, packages/wallet-frontend/src/lib/api/user.ts, packages/wallet-frontend/src/pages/settings/index.tsx
- #387 
Types update and small changes.
=> refactor(wallet-frontend): update user service

packages/wallet-backend-update/migrations/20230317142949_create_accounts.js, packages/wallet-backend-update/migrations/20230317143010_create_payment_pointers.js, packages/wallet-backend-update/src/account/controller.ts, packages/wallet-backend-update/src/account/service.ts, packages/wallet-backend-update/src/account/validation.ts, packages/wallet-backend-update/src/config/env.ts, packages/wallet-backend-update/src/global.d.ts, packages/wallet-backend-update/src/index.ts, packages/wallet-backend-update/src/utils/helpers.ts, packages/wallet-frontend/next-env.d.ts, packages/wallet-frontend/src/components/AccountCard.tsx, packages/wallet-frontend/src/components/dialogs/FundAccountDialog.tsx, packages/wallet-frontend/src/lib/api/account.ts, packages/wallet-frontend/src/lib/api/paymentPointer.ts, packages/wallet-frontend/src/pages/account/[accountId].tsx, packages/wallet-frontend/src/pages/account/[accountId]/[paymentPointerId].tsx, packages/wallet-frontend/src/pages/transfer/pay.tsx, packages/wallet-frontend/src/ui/forms/Input.tsx, packages/wallet-frontend/src/utils/helpers.ts
- #387 
- closes #363 
- Adds missing table column and fixes the column type for the asset code
- Retrieve the unformatted balance/amount from backend
- Adds missing prototype for `BigInt`
- Small refactoring
- Account service refactoring
- Improved balance/amount formatting 
- Input's add-on/trailing content now has the default font size
=> refactor: update account service

packages/wallet-backend-update/src/app.ts, packages/wallet-backend-update/src/asset/controller.ts, packages/wallet-frontend/src/lib/api/asset.ts, packages/wallet-frontend/src/pages/account/[accountId]/[paymentPointerId].tsx
- #387 
Removes `assets/:id` endpoint since the scale is now stored in the `accounts` table.
=> refactor: assets refactoring

packages/wallet-backend-update/src/incomingPayment/service.ts, packages/wallet-backend-update/src/utils/helpers.ts
- #387 
- `100.63` was returned as `100` when fetching the payment details
=> fix: format amount correctly when fetching payment details

.github/contributing.md, .github/labeler.yml, .github/pull_request_template.md, .github/workflows/ci.yml, .github/workflows/pr_labeler.yml, .github/workflows/pr_title_check.yml, .github/workflows/setup/action.yml, .prettierignore, .prettierrc.js, package.json
- #420 
- Update paths for `labeler`
- Update PR checks workflow
- Cancel previous workflow runs on a new push action if one is running
- Remove `.github` folder from `.prettierignore` and format all files
=> chore: update github workflows

.github/workflows/pr_title_check.yml
The title check should be run when the pull request is opened or synchronized as well.
=> chore: fix PR title check trigger

packages/wallet/backend/migrations/20230317143010_create_payment_pointers.js, packages/wallet/backend/migrations/20230317143023_create_transactions.js, packages/wallet/backend/migrations/20230626171045_update_transactions_field_types.js, packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/transaction/model.ts
- fixes #422 
- Alters transactions table to support saving account id, payment id to be a string and payment pointer to be nullable.
- Registers transactions for withdraw/fund account operations.
The transactions will not be displayed on frontend as the transaction table is for a payment pointer at the moment.
=> feat(transactions): add fund/withdraw transactions

packages/wallet/backend/src/asset/controller.ts, packages/wallet/backend/src/rafiki/rafiki-client.ts
=> fix(wallet/backend): fetch all assets

docker/prod/docker-compose.yml
=> build: forward admin port

docker/prod/docker-compose.yml
=> build: upgrade rafiki image to main

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/app.ts, packages/wallet/backend/src/paymentPointer/controller.ts, packages/wallet/backend/src/paymentPointer/model.ts, packages/wallet/backend/src/paymentPointer/service.ts, packages/wallet/frontend/src/lib/api/paymentPointer.ts, packages/wallet/frontend/src/pages/settings/developer-keys.tsx
=> feat(wallet/backend): add revoke payment pointer key

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> chore: update Rafiki frontend image

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> build: fix main image to the current hash

packages/wallet/frontend/src/lib/api/account.ts
=> fix: bug that less than 1 amount is not funding or withdrawing

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/rapyd/rapyd-client.ts, packages/wallet/backend/tests/account/controller.test.ts
=> fix(backend): rapyd temporary workaround

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/rapyd/rapyd-client.ts, packages/wallet/backend/tests/account/controller.test.ts
This reverts commit 909745a2024134d4e19b60f9e87d12ff95178f48.
=> fix: revert Rapyd temporary workaround

packages/wallet/backend/src/outgoingPayment/service.ts
=> fix(transactions): set outogoing currency from quote

.github/workflows/ci_deploy.yml
=> chore: run the release workflow on push

packages/wallet/backend/src/quote/service.ts, packages/wallet/backend/src/rafiki/rafiki-client.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/transaction/service.ts, packages/wallet/backend/src/utils/helpers.ts
- fixes #528 
- incoming payment created event is now available from rafiki
quote now properly handles fixed_delivery when already created incoming payment is used.
added webhook for incoming payment created event
=> fix(quote): Quote amount not set properly

docker/prod/docker-compose.yml
- fixes #
Adds `tigerbeetle-data` volume
=> chore: fix production compose file

packages/wallet/backend/src/incomingPayment/validation.ts
- hotfix: update validation schema for incoming payment url
=> fix: allow hyphens for PP name when fetching IP details

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/incomingPayment/service.ts, packages/wallet/backend/src/incomingPayment/validation.ts, packages/wallet/backend/src/quote/service.ts, packages/wallet/backend/src/rafiki/rafiki-client.ts
=> chore: release

packages/wallet/backend/src/quote/service.ts
=> fix: set asset from payment pointer

packages/wallet/frontend/package.json, pnpm-lock.yaml
This reverts commit 39fabb12c06f1744a9eea545627f62ad09d380ee.
- fixes #
=> chore(deps): revert - update nextjs monorepo to ^13.4.13 (#595)

packages/commerce/backend/migrations/20230809220722_add_products_table.js, packages/commerce/backend/migrations/20230809222011_add_users_table.js, packages/commerce/backend/migrations/20230810053817_add_orders_table.js, packages/commerce/backend/migrations/20230810055919_add_order_items_table.js
- closes #593 
This is the initial database schema. Things might change later.
=> feat(commerce/backend): add migrations

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml, packages/wallet/backend/src/quote/service.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/frontend/src/pages/transfer/send.tsx
=> feat: make use of Rafiki's rates service changes

packages/wallet/backend/src/quote/service.ts
Fixes some conversion issues when calculating fees.
=> feat(wallet/backend): fix conversions

packages/commerce/backend/migrations/20230809220722_add_products_table.js, packages/commerce/backend/migrations/20230809222011_add_users_table.js, packages/commerce/backend/migrations/20230810053817_add_orders_table.js, packages/commerce/backend/package.json, packages/commerce/backend/src/app.ts, packages/commerce/backend/src/container.ts, packages/commerce/backend/src/order/model.ts, packages/commerce/backend/src/order/service.ts, packages/commerce/backend/src/orderItem/model.ts, packages/commerce/backend/src/product/model.ts, packages/commerce/backend/src/product/service.ts, packages/commerce/backend/src/shared/model.ts, packages/commerce/backend/src/shared/utils.ts, packages/commerce/backend/src/user/model.ts, packages/commerce/backend/src/user/service.ts, packages/commerce/backend/tests/app.test.ts, packages/commerce/backend/tests/app.ts, packages/commerce/backend/tests/helpers.ts, packages/commerce/backend/tests/mocks.ts, packages/commerce/backend/tests/order/service.test.ts, packages/commerce/backend/tests/product/service.test.ts, packages/commerce/backend/tests/tables.ts, packages/commerce/backend/tests/user/service.test.ts
=> feat(commerce/backend): add objection models and services

.github/labeler.yml, .github/workflows/ci.yml
=> chore(ci): add commerce app to workflows

packages/commerce/frontend/src/app/cart/components/cart-item.tsx, packages/commerce/frontend/src/app/cart/components/cart-items.tsx, packages/commerce/frontend/src/app/cart/components/order-summary.tsx, packages/commerce/frontend/src/app/cart/index.tsx, packages/commerce/frontend/src/app/cart/routes.tsx, packages/commerce/frontend/src/app/index.tsx, packages/commerce/frontend/src/app/products/components/product-card.tsx, packages/commerce/frontend/src/app/products/components/product-cta.tsx, packages/commerce/frontend/src/app/products/components/product-shimmer.tsx, packages/commerce/frontend/src/components/icons.tsx, packages/commerce/frontend/src/components/navigation.tsx, packages/commerce/frontend/src/components/shopping-cart-popover.tsx, packages/commerce/frontend/src/components/ui/button.tsx, packages/commerce/frontend/src/components/ui/toast.tsx, packages/commerce/frontend/src/lib/stores/cart-store.ts, packages/commerce/frontend/tailwind.config.cjs
=> feat(commerce/frontend): add shopping cart page

packages/wallet/backend/src/rafiki/service.ts
=> feat(backend): Add temporary fees for multiple assets

packages/wallet/backend/src/auth/controller.ts, packages/wallet/backend/src/middleware/errorHandler.ts, packages/wallet/backend/src/paymentPointer/controller.ts, packages/wallet/backend/src/user/controller.ts
- fixes #571
- removes duplicate log of errors from controller as they are handled in the middleware (they were causing unnecessary noise). If any of them are required, a log should be added before throwing the error
- separate handle of axios error is added to log the message and the response for debugging
=> feat(middleware): add handling of axios errors

packages/wallet/backend/src/incomingPayment/service.ts, packages/wallet/backend/src/rafiki/auth/generated/graphql.ts, packages/wallet/backend/src/rafiki/backend/generated/graphql.ts, packages/wallet/backend/src/rafiki/backend/request/receiver.request.ts, packages/wallet/backend/src/rafiki/controller.ts, packages/wallet/backend/src/rafiki/rafiki-client.ts, packages/wallet/backend/src/rafiki/validation.ts
=> feat(payments): create external receiver

packages/wallet/backend/package.json, pnpm-lock.yaml
https://github.com/interledger/testnet/security/dependabot/3
=> fix(deps): update dependency graphql to ^16.8.1

.github/contributing.md
- fixes Contribution guide
Added additional sections to the contribution guide to help new contributors.
=> chore: added additional sections to Contribution guide

packages/wallet/frontend/src/components/onboarding/Onboarding.tsx, packages/wallet/frontend/src/pages/grant-interactions/index.tsx
=> feat(wallet-frontend): Feedback changes for texts

packages/wallet/backend/src/outgoingPayment/service.ts, packages/wallet/backend/src/utils/helpers.ts
=> fix(payment): continue payment if it is not internal

packages/wallet/backend/tests/mocks.ts, packages/wallet/backend/tests/rapyd/controller.test.ts, packages/wallet/backend/tests/rapyd/service.test.ts
=> feat: Add unit tests for rapyd controllers and services

README.md
- fixes #833
Changed https://interledger.org/rfcs/0027-interledger-protocol-4/ to https://interledger.org/developers/rfcs/interledger-protocol/ in the
=> fix: Interledger Link in README.md

packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/rapyd/rapyd-client.ts
- fixes #741
Automatically adds liquidity into rapyd settlement account. As deposit does not work for client wallet, we will need to switch to a created user wallet as a settlement one.
=> feat: deposit additional rapyd funds

packages/wallet/frontend/src/components/cards/PaymentPointerCard.tsx
If the PR is related to an open issue(s) please provide a list of them.
Closes #814
Added copy button for PP
=> feat(wallet-frontend): Add copy button for PP interledger#814

.github/workflows/ci.yml, docker/dev/docker-compose.yml, packages/wallet/backend/jest.setup.js, packages/wallet/backend/jest.teardown.js, packages/wallet/backend/src/app.ts, packages/wallet/backend/src/createContainer.ts, packages/wallet/backend/src/paymentPointer/service.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/transaction/model.ts, packages/wallet/backend/src/transaction/service.ts, packages/wallet/backend/src/webMonetization/transaction/model.ts, packages/wallet/backend/src/webMonetization/transaction/service.ts, packages/wallet/backend/tests/account/controller.test.ts, packages/wallet/backend/tests/app.test.ts, packages/wallet/backend/tests/asset/controller.test.ts, packages/wallet/backend/tests/auth/controller.test.ts, packages/wallet/backend/tests/auth/service.test.ts, packages/wallet/backend/tests/quote/controller.test.ts, packages/wallet/backend/tests/quote/service.test.ts, packages/wallet/backend/tests/rapyd/controller.test.ts, packages/wallet/backend/tests/rapyd/service.test.ts, packages/wallet/backend/tests/socket/service.test.ts, packages/wallet/backend/tests/transaction/service.test.ts, packages/wallet/backend/tests/user/controller.test.ts, packages/wallet/backend/tests/user/service.test.ts
=> feat(wm): update webhook handling and transactions service

packages/wallet/backend/src/quote/service.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/utils/helpers.ts, packages/wallet/backend/tests/quote/service.test.ts
=> feat: remove websocket notification for Exchange

packages/wallet/frontend/src/pages/account/[accountId].tsx
- fixes #931 
- remove highlight for Accoun tabs
- make sure PPs in list have $ for url and not https://
=> fix(wallet/frontend): payment pointer format and focus

packages/boutique/backend/Dockerfile.dev, packages/wallet/backend/Dockerfile.dev, packages/wallet/backend/src/paymentPointer/service.ts, packages/wallet/frontend/Dockerfile.dev, packages/wallet/frontend/src/components/TemporaryWMNotice.tsx, packages/wallet/frontend/src/components/dialogs/CreatePaymentPointerDialog.tsx, packages/wallet/frontend/src/pages/account/[accountId].tsx
=> feat(wallet): WM only for USD accounts

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> chore: update Rafiki to alpha 5

packages/wallet/backend/package.json, pnpm-lock.yaml
https://github.com/interledger/testnet/security/dependabot/8
=> fix(deps): bump `crypto-js` version to `4.2.0`

packages/wallet/backend/tests/auth/controller.test.ts, packages/wallet/backend/tests/auth/service.test.ts
=> feat: updated Auth unit test

packages/wallet/frontend/package.json, pnpm-lock.yaml
Reverts interledger/testnet#610
=> chore(deps): revert update nextjs monorepo to ^13.5.6

packages/wallet/backend/tests/transaction/controller.test.ts, packages/wallet/backend/tests/transaction/service.test.ts
=> feat: added unit tests for the Transaction controller& service

packages/boutique/backend/src/container.ts, packages/wallet/frontend/src/pages/grant-interactions/index.tsx
=> fix(grant): show outgoing payment access info on interaction

packages/wallet/frontend/src/pages/grant-interactions/index.tsx
=> feat(grants): show interaction only for PENDING grants

packages/wallet/backend/src/app.ts, packages/wallet/backend/src/user/controller.ts, packages/wallet/backend/src/user/service.ts, packages/wallet/backend/src/user/validation.ts, packages/wallet/backend/tests/user/controller.test.ts, packages/wallet/frontend/src/components/providers/PasswordProvider.tsx, packages/wallet/frontend/src/components/providers/index.tsx, packages/wallet/frontend/src/components/settings/ChangePasswordForm.tsx, packages/wallet/frontend/src/components/settings/PersonalSettingsForm.tsx, packages/wallet/frontend/src/lib/api/user.ts, packages/wallet/frontend/src/lib/context/password.ts
- fixes #773 
- On the Settings page there is a new button 'Change Password' and the old password ca be exchanged for a new one.
- All validations for old password, and new password are in place
=> feat: Change password feature implemented in settings page

packages/wallet/frontend/src/components/onboarding/Onboarding.tsx
=> fix: Update Onboarding to work only with tooltip

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> chore: add logging size limit

packages/wallet/backend/src/rafiki/auth/generated/graphql.ts, packages/wallet/backend/src/rafiki/auth/request/grant.request.ts, packages/wallet/backend/src/rafiki/backend/generated/graphql.ts, packages/wallet/frontend/src/components/GrantDetails.tsx, packages/wallet/frontend/src/lib/api/grants.ts, packages/wallet/frontend/src/pages/account/[accountId].tsx, packages/wallet/frontend/src/pages/grant-interactions/index.tsx, packages/wallet/frontend/src/pages/grants/[grantId].tsx, packages/wallet/frontend/src/pages/grants/index.tsx, packages/wallet/frontend/src/pages/settings/developer-keys.tsx, packages/wallet/frontend/src/pages/transfer/request.tsx, packages/wallet/frontend/src/pages/transfer/send.tsx, packages/wallet/frontend/src/ui/Badge.tsx, packages/wallet/frontend/src/utils/helpers.ts
- fixes #1129 
- added new types into Grants and the reason of Finalization - Issued- Rejected-Revoked
- Further fixes for grants regarding contrasting buttons and wallet address display
=> fix: update grants types after rafiki change

packages/wallet/backend/src/rapyd/schemas.ts
=> fix: update rapyd transfer response schema

packages/wallet/backend/src/email/service.ts
=> fix: skip setting SG api key when send email is disabled

.github/TESTNET_architecture.md, README.md
=> feat: Add architecture diagramm to testnet

docker/prod/docker-compose.yml, packages/boutique/backend/package.json, packages/boutique/backend/src/config/logger.ts, packages/wallet/backend/package.json, packages/wallet/backend/src/config/logger.ts, pnpm-lock.yaml
=> chore: change prod log driver to gcp

packages/boutique/backend/src/open-payments/service.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/socket/messageType.ts, packages/wallet/backend/src/socket/service.ts, packages/wallet/backend/tests/socket/service.test.ts, packages/wallet/frontend/src/pages/_app.tsx
- Add new metadata filed to outgoing openPayment
- fixes #835
=> feat: Websocket notification for Grant Withdraw

packages/wallet/backend/tests/walletAddressKeys/controller.test.ts, packages/wallet/backend/tests/walletAddressKeys/service.test.ts
=> test: add developer keys tests

packages/wallet/frontend/package.json, packages/wallet/frontend/src/components/onboarding/Onboarding.tsx, pnpm-lock.yaml
- fixes #1150 
Onboarding started working differently since a while ago, showing beacins, and doing weird jumps, also allowing user to click on the overlay. Reverted React-Jouyride to initial version when Onboarding was implemented.
=> fix: Fix onboarding by downgrading

packages/wallet/backend/migrations/20240306113102_default_keys_nickname.js, packages/wallet/backend/src/user/service.ts, packages/wallet/backend/src/walletAddressKeys/controller.ts, packages/wallet/backend/src/walletAddressKeys/model.ts, packages/wallet/backend/src/walletAddressKeys/service.ts, packages/wallet/backend/src/walletAddressKeys/validation.ts
=> feat: make key nickname required

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml, packages/boutique/backend/package.json, pnpm-lock.yaml
=> chore: upgrade rafiki  to alpha 7

packages/wallet/backend/src/app.ts
=> fix: remove rate limit on signup

packages/wallet/frontend/src/components/settings/ChangePasswordForm.tsx, packages/wallet/frontend/src/components/settings/PersonalSettingsForm.tsx, packages/wallet/frontend/src/pages/account/create.tsx, packages/wallet/frontend/src/pages/auth/forgot.tsx, packages/wallet/frontend/src/pages/auth/login.tsx, packages/wallet/frontend/src/pages/auth/signup.tsx, packages/wallet/frontend/src/pages/exchange.tsx
- fixes https://github.com/interledger/testnet/issues/809
* Added focus to the first focusable input element on component load across multiple components in wallet
=> chore: added focus to the first focusable elements on component load

packages/wallet/backend/src/transaction/service.ts
=> fix: check for existing transaction

packages/boutique/backend/src/app.ts, packages/boutique/backend/src/order/controller.ts, packages/boutique/backend/src/product/controller.ts
=> feat(boutique): refactor controller functions to arrow functions

packages/boutique/backend/src/app.ts, packages/boutique/backend/src/index.ts, packages/wallet/backend/src/index.ts
=> fix: start background processing only if the app started

packages/shared/backend/src/configs/logger.ts, packages/wallet/backend/src/rafiki/controller.ts, packages/wallet/backend/src/rapyd/rapyd-client.ts
=> feat(webhook): add context to errors

packages/shared/backend/src/configs/logger.ts, packages/wallet/backend/src/config/logger.ts
=> fix: pass correct env to logger

.nvmrc
=> chore: update `.nvmrc`

packages/wallet/backend/src/rapyd/schemas.ts, packages/wallet/backend/src/rapyd/service.ts
=> fix: add required field to rapyd contact

packages/wallet/backend/src/email/templates/verifyEmail.ts, packages/wallet/frontend/src/components/Menu.tsx, packages/wallet/frontend/src/pages/auth/signup.tsx, packages/wallet/frontend/src/pages/auth/verify/[token].tsx
=> fix(1289): change name to "test wallet"

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> chore: upgrade to rafiki alpha 9

packages/wallet/frontend/src/components/onboarding/OnboardingTooltip.tsx, packages/wallet/frontend/src/pages/account/[accountId].tsx
- fixes https://github.com/interledger/testnet/issues/1264
* The onboarding steps are changed to EUR account, Accordingly updated the steps
* Adjusted the onboarding step 8 image dimensions of the icon
=> fix: 1264 fixed the onboarding steps

.github/workflows/build-publish.yaml
Use latest pnpm version in workflow
=> fix(workflows): use latest pnpm version

.github/workflows/build-publish.yaml
use name in docker image instead of identifier
=> feat(workflows): latest pnpm

packages/boutique/shared/index.ts, packages/boutique/shared/package.json, pnpm-lock.yaml
=> chore: move index.ts and update package.json

.gitignore, packages/wallet/frontend/src/components/TransferHeader.tsx, packages/wallet/frontend/src/pages/transfer/request.tsx, packages/wallet/frontend/src/pages/transfer/send.tsx
In transfer pages, added pageHeader and value placeholder, adjusted display of transfer header, label update
- fixes #1311
=> feat(1311): update transfer pages ux

package.json, packages/boutique/backend/Dockerfile.dev, packages/boutique/backend/Dockerfile.prod, packages/boutique/backend/package.json, packages/boutique/frontend/Dockerfile.prod, packages/wallet/backend/Dockerfile.dev, packages/wallet/backend/Dockerfile.prod, packages/wallet/frontend/Dockerfile.dev
=> chore: upgrade pnpm

.github/TESTNET_architecture.md, .github/contributing.md, README.md, packages/wallet/backend/src/email/templates/forgotPassword.ts, packages/wallet/backend/src/email/templates/verifyEmail.ts, packages/wallet/frontend/src/components/onboarding/Onboarding.tsx, packages/wallet/frontend/src/pages/auth/reset/[token].tsx
- fixes #1317 
- Testnet should be Test Network when talking about Test Wallet and Boutique together, then rename to Test Wallet, when talking about the wallet.
=> fix: Rename Testnet

packages/wallet/frontend/src/components/dialogs/QuoteDialog.tsx, packages/wallet/frontend/src/pages/transfer/send.tsx
- fixes #1331 
- Some text changes on Quote to make it more friendly
- Show PP Public Name if available
=> fix: Quote text changes

packages/wallet/frontend/src/pages/transactions.tsx, packages/wallet/frontend/src/styles/main.css
- fixes #1326 
- renamed header of column to Payment Pointer Name
- added on hover a tooltip to display full url of PP
=> fix: Add payment pointer full url tooltip to transaction list

packages/wallet/backend/src/grant/controller.ts, packages/wallet/frontend/src/components/GrantDetails.tsx, packages/wallet/frontend/src/lib/api/grants.ts, packages/wallet/frontend/src/lib/hooks/useGrants.ts, packages/wallet/frontend/src/pages/grant-interactions/index.tsx, packages/wallet/frontend/src/pages/grants/[grantId].tsx, packages/wallet/shared/src/types/grant.ts, packages/wallet/shared/src/types/index.ts
=> feat: bring grant response type into shared package

packages/wallet/frontend/src/styles/main.css, packages/wallet/frontend/tailwind.config.js
=> chore: update tailwind config

packages/wallet/frontend/src/ui/TogglePayment.tsx
=> fix: Update tooltip on send page

packages/boutique/backend/src/order/controller.ts, packages/wallet/frontend/src/pages/grants/[grantId].tsx
=> feat: Display revoke button for recurring payments

packages/wallet/frontend/src/pages/request.tsx, packages/wallet/frontend/src/pages/send.tsx, packages/wallet/frontend/src/ui/Badge.tsx
=> fix: badge update for transfer pages

packages/wallet/backend/src/grant/service.ts
=> fix: keep request grants filters

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
- bump(prod): rafiki to alpha 15
- bump(dev): rafiki to alpha 15
It will upgrade rafiki to version alpha.15
=> feat(rafiki): upgrade to alpha15

docker/dev/kratos.yml
=> chore: fix kratos config

packages/wallet/backend/src/walletAddressKeys/service.ts, packages/wallet/backend/tests/walletAddressKeys/service.test.ts, packages/wallet/frontend/src/pages/grant-interactions/index.tsx
=> fix: fix upload repetitive key into the Rafiki

packages/wallet/frontend/src/components/GrantDetails.tsx, packages/wallet/frontend/src/pages/grant-interactions/index.tsx, packages/wallet/frontend/src/pages/grants/index.tsx
- fixes #1389 
- updates grant interaction pages
- updates grant list page
- updated grant details page
=> feat: New design grants pages

packages/wallet/frontend/src/pages/exchange.tsx
=> feat: add  assetScale 2 filter for assets in exchange page

docker/dev/docker-compose.yml, packages/wallet/backend/src/createContainer.ts, packages/wallet/backend/src/rafiki/kratos.service.ts, packages/wallet/backend/src/user/service.ts
=> feat: add default user to rafiki admin

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml, packages/wallet/backend/src/rafiki/backend/generated/graphql.ts, packages/wallet/backend/src/rafiki/backend/request/outgoing-payment.request.ts, packages/wallet/backend/src/rafiki/backend/request/quote.request.ts
=> feat: upgrade rafiki to alpha 16

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
- Update rafiki to alpha v 17 (hotfix)
=> chore: update to rafiki alpha 17

packages/wallet/backend/src/config/env.ts, packages/wallet/backend/src/gatehub/client.ts, packages/wallet/backend/src/gatehub/consts.ts, packages/wallet/backend/src/gatehub/types.ts, packages/wallet/frontend/src/pages/grant-interactions/index.tsx
=> feat: implement initial gatehub client

packages/wallet/frontend/src/pages/grant-interactions/index.tsx
- fixes #1551 
center IDP page modal
=> fix: center IDP page

packages/wallet/backend/src/email/templates/forgotPassword.ts, packages/wallet/backend/src/user/service.ts
- fixes #1541 
- set password reset token expire after 12h
=> fix: forgotten password - extend reset token expire time

packages/wallet/frontend/src/lib/api/user.ts
- fixes #1561
Added password complexity for security reasons.
Regex check for - at least one special char, and number
Regex check for uppercase and lowercase letters
=> fix: Improve password complecxity for security reasons

packages/wallet/frontend/src/lib/api/user.ts
- fixes #1565 
- added password complexity constraint to forgotten password
- added password complexity constarint to change password
=> fix: add password complexity constraint everywhere where needed

packages/wallet/frontend/src/pages/account/[accountId].tsx
- fixes #1567 
Added back code for new design layout for account details page.
=> fix: fix wrongly rebased PR for WM PPs removal

packages/wallet/frontend/src/components/userCards/UserCardActions.tsx, packages/wallet/frontend/tailwind.config.js
- fixes #1569 
- added hover button layout for light mode buttons with only icon inside
=> feat: button hover actions

packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx
=> fix: remove className form transition

packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx
=> fix: developer keys headless UI bug fix

packages/wallet/backend/tests/walletAddressKeys/service.test.ts
=> test(wallet/backend): fix wallet address keys test

packages/wallet/frontend/src/components/userCards/UserCardActions.tsx, packages/wallet/frontend/src/components/userCards/UserCardSettings.tsx
=> fix(wallet/frontend): update card key icon and button sizes

packages/shared/backend/src/errors/index.ts, packages/shared/backend/src/errors/not-verified.ts, packages/wallet/backend/src/app.ts, packages/wallet/backend/src/auth/controller.ts, packages/wallet/backend/src/auth/service.ts, packages/wallet/backend/src/auth/validation.ts, packages/wallet/backend/src/user/service.ts, packages/wallet/backend/src/user/validation.ts, packages/wallet/backend/tests/auth/controller.test.ts, packages/wallet/backend/tests/auth/service.test.ts, packages/wallet/frontend/src/lib/api/user.ts, packages/wallet/frontend/src/pages/auth/forgot.tsx, packages/wallet/frontend/src/pages/auth/login.tsx, packages/wallet/shared/src/types/user.ts
- fixes #1560 
- add support to resend account validation email
=> fix: Resend verification email

packages/wallet/backend/src/gatehub/client.ts, packages/wallet/backend/src/gatehub/controller.ts
Fixes for #1546 and #1591.
- Adds missing awaits
- Fixes scope for the widget URL generator methods
=> fix(wallet/backend): add missing awaits; fix scope for gatehub client

packages/wallet/frontend/src/lib/types/windowMessages.ts
Extracted from #1530 - to be used in #1537 & #1539 as well.
=> feat(wallet/frontend): add window message types

packages/wallet/frontend/src/components/GrantDetails.tsx, packages/wallet/frontend/src/pages/grants/index.tsx
- fixes #1439 
- update grants status badge text per right status reason
=> fix: update grants status badge text per right status reason

packages/wallet/frontend/src/pages/transactions.tsx, packages/wallet/frontend/src/styles/main.css, packages/wallet/frontend/src/ui/TogglePayment.tsx
=> fix(wallet/frontend): move all tooltips to Radix

packages/wallet/frontend/src/components/userCards/UserCardSettings.tsx
- fixes #1608 
- added dark an light hover states for card settings buttons
=> feat: hover state for Card Settings

packages/wallet/frontend/src/components/settings/ChangePasswordForm.tsx, packages/wallet/frontend/src/components/settings/PersonalSettingsForm.tsx, packages/wallet/frontend/src/lib/api/user.ts, packages/wallet/frontend/src/pages/auth/login.tsx, packages/wallet/frontend/src/pages/auth/reset/[token].tsx, packages/wallet/frontend/src/pages/auth/signup.tsx, packages/wallet/frontend/src/pages/settings/index.tsx
=> fix(wallet/frontend): update account settings page

packages/wallet/backend/src/email/templates/forgotPassword.ts, packages/wallet/backend/src/email/templates/verifyEmail.ts
- fixes #1584 
correction in email template for link to main
=> fix: correction in email template for link to main

packages/boutique/frontend/Dockerfile.prod
=> fix(rafiki-boutique-frontend): eslint to eslint config mjs

packages/wallet/backend/src/app.ts
Since cards are not going to be available on staging, a middleware was added to ensure that the cards API are only available in production.
=> feat(wallet/backend): lock cards API for staging

packages/shared/backend/package.json, packages/shared/backend/src/configs/logger.ts, pnpm-lock.yaml
=> fix(shared): remove GCP logging transport

packages/boutique/frontend/src/app/cart/components/cart-items.tsx, packages/boutique/frontend/src/app/products/$slug.tsx, packages/boutique/frontend/src/components/layouts/base.tsx, packages/boutique/frontend/src/components/shopping-cart-popover.tsx
=> fix: Fix boutique image issues

README.md, packages/boutique/backend/src/open-payments/service.ts, packages/wallet/backend/src/email/service.ts, packages/wallet/backend/src/email/templates/forgotPassword.ts, packages/wallet/backend/src/email/templates/verifyEmail.ts, packages/wallet/frontend/src/pages/_app.tsx
=> fix: Replace rafiki money and boutique with correct names

packages/wallet/frontend/src/utils/constants.ts
=> fix(wallet/frontend): temporary hardcoded value for staging

packages/wallet/backend/src/gatehub/client.ts
=> fix(wallet/backend): provide correct rates to rafiki

packages/wallet/backend/src/email/templates/forgotPassword.ts, packages/wallet/backend/src/email/templates/verifyEmail.ts, packages/wallet/frontend/src/components/HeaderLogo.tsx, packages/wallet/frontend/src/components/dialogs/DepositDialog.tsx, packages/wallet/frontend/src/components/layouts/AuthLayout.tsx, packages/wallet/frontend/src/pages/kyc.tsx
- fixes #1737 
- small frontend fixes and improvements
=> fix: Post deployment small fixes and improvements

.github/workflows/build-publish.yaml, packages/wallet/frontend/next.config.js, packages/wallet/frontend/src/utils/constants.ts
=> chore(ci): fix build

.github/workflows/build-publish.yaml, packages/wallet/frontend/src/components/dialogs/DepositDialog.tsx
$ instead of https for open payments domain env vars
- fixes #
=> chore(ci): fix open payments host

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/gatehub/consts.ts, packages/wallet/backend/src/gatehub/types.ts
=> fix(wallet/backend): update vault ids; remove fees

packages/wallet/backend/src/user/controller.ts
=> feat(user): update session if kyc was verified

packages/wallet/backend/src/app.ts, packages/wallet/backend/src/card/controller.ts, packages/wallet/backend/src/card/service.ts, packages/wallet/backend/src/card/validation.ts, packages/wallet/backend/src/gatehub/client.ts, packages/wallet/backend/tests/cards/controller.test.ts
- fixes #1670
- Change pin endpoint is updated to reflect the new flow
- Proxy urls are updated as well
=> feat(wallet/backend): fix change pin endpoint

packages/wallet/backend/src/card/service.ts
=> fix(wallet/backend): fix CI

packages/wallet/backend/src/gatehub/controller.ts, packages/wallet/backend/src/gatehub/service.ts
store gatehub userState even if user was in manual approve flow
Include logs for user connected to gateway
=> feat(wallet-backend): handle manual approve flow

packages/wallet/backend/src/app.ts
=> fix: temporary disable the signature

packages/wallet/backend/src/app.ts, packages/wallet/backend/src/gatehub/service.ts
=> fix: fix user id

packages/wallet/backend/src/socket/service.ts
socket logs moved to debug level to remove clutter
=> feat(wallet/backend): socket logs are now debug level

packages/wallet/backend/src/rafiki/service.ts
=> fix: add optional on metadata

packages/wallet/backend/src/app.ts, packages/wallet/backend/src/middleware/isGateHubSignedWebhook.ts
=> fix: enable gatehub signature check

packages/wallet/backend/src/gatehub/consts.ts
=> feat: add MXN support on test wallet

packages/wallet/backend/migrations/20241022161159_add_status_flags_to_users.js, packages/wallet/backend/src/email/service.ts, packages/wallet/backend/src/email/templates/actionRequiredEmail.ts, packages/wallet/backend/src/email/templates/rejectEmail.ts, packages/wallet/backend/src/gatehub/service.ts, packages/wallet/backend/src/gatehub/types.ts, packages/wallet/backend/src/user/model.ts
=> feat: handle webhooks

packages/wallet/backend/migrations/20241023143459_card_wallet_address_to_users.js, packages/wallet/backend/src/gatehub/service.ts, packages/wallet/backend/src/user/model.ts
=> feat: add card WA to user

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/gatehub/service.ts
=> fix: get user card id

packages/wallet/backend/src/gatehub/service.ts
=> fix: save user info before approving

packages/wallet/backend/migrations/20241023200155_add_is_card_to_transactions.js, packages/wallet/backend/migrations/20241024200455_add_is_card_to_wallet_addresses.js, packages/wallet/backend/src/gatehub/service.ts, packages/wallet/backend/src/gatehub/types.ts, packages/wallet/backend/src/transaction/model.ts, packages/wallet/backend/src/walletAddress/model.ts, packages/wallet/backend/src/walletAddress/service.ts, packages/wallet/shared/src/types/card.ts
=> feat: insert card transactions

packages/wallet/backend/src/app.ts, packages/wallet/backend/src/card/controller.ts, packages/wallet/backend/src/card/service.ts, packages/wallet/backend/src/card/validation.ts, packages/wallet/frontend/src/components/dialogs/PasswordDialog.tsx, packages/wallet/frontend/src/components/dialogs/UserCardPINDialog.tsx, packages/wallet/frontend/src/components/userCards/UserCardActions.tsx, packages/wallet/frontend/src/components/userCards/UserCardSettings.tsx, packages/wallet/frontend/src/lib/api/card.ts, packages/wallet/frontend/src/lib/api/user.ts
=> feat(wallet): ask for user password on certain card actions

packages/wallet/backend/src/email/service.ts, packages/wallet/backend/src/email/templates/kycVerifiedEmail.ts, packages/wallet/backend/src/email/templates/verifyEmail.ts
=> fix(wallet/backend): update email templates

docker/dev/docker-compose.yml, docker/prod/docker-compose.yml
=> feat: upgrade rafiki to alpha 20

packages/wallet/frontend/src/components/WalletAddressesTable.tsx, packages/wallet/shared/src/types/walletAddress.ts
=> feat(wallet/frontend): use custom domain for card pp

packages/wallet/frontend/src/components/WalletAddressesTable.tsx, packages/wallet/frontend/src/pages/index.tsx
=> fix(wallet/frontend): fix pp for card

packages/wallet/frontend/src/pages/auth/login.tsx, packages/wallet/frontend/src/pages/auth/signup.tsx
=> fix: login fixes

packages/wallet/backend/src/rafiki/rafiki-client.ts, packages/wallet/backend/src/utils/helpers.ts, packages/wallet/backend/src/walletAddress/service.ts
=> feat: replace ip dev

packages/wallet/backend/src/transaction/service.ts
=> fix: set currency to euro

packages/wallet/backend/src/transaction/service.ts
=> fix: check new transactions length

packages/wallet/backend/src/account/service.ts, packages/wallet/backend/src/gatehub/consts.ts, packages/wallet/backend/src/gatehub/service.ts, packages/wallet/backend/src/gatehub/types.ts
=> feat: save deposit transactions

packages/boutique/frontend/src/app/checkout/components/order-summary.tsx
=> fix: Update order-summary fees text

packages/boutique/frontend/src/components/bubbles.tsx, packages/boutique/frontend/src/components/navigation.tsx, packages/boutique/frontend/src/components/ui/sheet.tsx
=> fix: Update mobile menu navigation

packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx, packages/wallet/frontend/src/ui/Button.tsx
- fixes #1353 
- after some discussions with Madalina, we removed some delimiting lines, made bigger spaces between accounts, and made the buttons smaller
=> fix: Change dev keys to make it more user friendly

packages/wallet/frontend/src/pages/kyc.tsx
- fixes #
Removes the check for FEATURES_ENABLED for adding user to gateway call as test wallet does not have them enabled but the user should be autoapproved.
=> fix: add user to gateway on test wallet

packages/wallet/backend/src/backfillTrxDetails.ts, packages/wallet/backend/src/rafiki/backend/generated/graphql.ts, packages/wallet/backend/src/rafiki/backend/request/incoming-payment.request.ts, packages/wallet/backend/src/rafiki/backend/request/outgoing-payment.request.ts, packages/wallet/backend/src/rafiki/rafiki-client.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/walletAddress/service.ts, packages/wallet/frontend/next.config.js
=> feat(transaction): add backfill trx details script

packages/wallet/frontend/src/components/dialogs/TransactionDetailsDialog.tsx
=> fix: card PP correct name, and card type fix

packages/wallet/frontend/src/components/dialogs/TransactionDetailsDialog.tsx, packages/wallet/frontend/src/pages/transactions.tsx
=> fix: transactions details cards pp is not ilpdev

packages/wallet/backend/src/rafiki/validation.ts
=> fix: add additional fields

packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/rafiki/validation.ts, packages/wallet/backend/tests/rafiki/controller.test.ts, packages/wallet/backend/tests/rafiki/service.test.ts
- fixes #
- remove double validation of the webhook
- change schemas according to [specs](https://github.com/interledger/rafiki/blob/main/packages/backend/src/openapi/specs/webhooks.yaml)
=> fix: change webhook validation according to specs

packages/wallet/backend/src/gatehub/consts.ts
- fixes #
- ADD SGD vault id for gatehub staging
=> fix: add sandbox gatehub vault id for SGD

packages/wallet/backend/src/gatehub/service.ts
=> fix(deposit): solve issue with deposit transactions for 1K+

packages/wallet/backend/migrations/20250217140155_second_party_pp_to_transactions.js, packages/wallet/backend/src/backfillTrxDetails.ts, packages/wallet/backend/src/rafiki/service.ts, packages/wallet/backend/src/transaction/model.ts, packages/wallet/backend/src/transaction/service.ts, packages/wallet/shared/src/types/transaction.ts
=> feat: add second party wallet address

packages/wallet/backend/src/grant/service.ts
- Improves error message #1917
=> fix: improve error message for invalid interaction

packages/wallet/backend/src/account/validation.ts, packages/wallet/backend/src/app.ts, packages/wallet/backend/src/quote/controller.ts, packages/wallet/backend/src/quote/service.ts
=> fix: remove exhange endpoint
