interledger/testnet

- packages/wallet/package.json
- packages/wallet/src/ui/Button.tsx
- packages/wallet/src/ui/ButtonOrLink.tsx
- packages/wallet/src/ui/Link.tsx
- pnpm-lock.yaml
- `ButtonOrLink` helper component
- `Button` and `Link` component that are using `ButtonOrLink`
`ButtonOrLink` component renders a `button` or an `a`, based on the props that are passed to it.
> feat(wallet): add button/link component

- packages/backend/src/auth/auth.service.ts
- packages/backend/src/auth/models/refreshToken.ts
fixes #140 
the bug was related to using objection .patch() without providing the id of the patched item.
Extracted the expiresInToExpiresAt into a static method of the RefreshToken class. It is now used in the constructor and in the auth service as well. This way, new Tokens are no longer instantiated when having to update older ones.
> fix: cookie issues for login and refresh

- packages/backend/src/auth/auth.service.ts
- packages/backend/src/auth/jwtStrategy.ts
-closes #157 
Users without the provided KYC do not have associated rapyd wallets. 
As such, users that only registered in testnet, but did not yet provide the KYC should not be allowed elsewhere except the KYC form page.
This PR implements blocking of any other authenticated  (protected) route  for users that did not yet provide a KYC from a backend perspective
- When a user logs in, backend check if he has a rapydId associated to his account. If not, it encodes the "noKyc" flag in the access token returned on the login endpoint. 
Further requests received from a user that has a noKyc flag in his access token get rejected with a 401 Unauthorised, unless the request.url is aimed at /createWallet (which is the endpoint through which the user actually provides the kyc)
- Email of the user …
> feat(noKYC): Backend blocks access to protected routes for users without kyc

- packages/backend/src/auth/auth.service.ts
- packages/backend/src/routes.ts
- packages/backend/src/shared/models/errors/NotFoundException.ts
Issued for #161 (just the backend support)
NextJS needs a middleware to decide if the user is authenticated or not before rendering pages. 
As such, a /me endpoint that acts as a user profile GET would be benefic
Introduced the /me endpoint, that returns the no-kyc information and acts as an "is authenticated" middelware for nextjs
> feat(noKyc): Add me endpoint to be used as authenticated middleware by next

- docker/dev/docker-compose-legacy.yml
- When merging the new backend scaffold, we moved the current backend into the `docker-compose-legacy.yml`. I forgot to add the new environment variable `RAPYD_SETTLEMENT_EWALLET` to it.
> fix: add missing env variable for legacy compose

- docker/dev/local-http-signatures/Dockerfile
```
=> CACHED [ 2/10] WORKDIR /workspace                                                                                                      0.0s
=> CACHED [ 3/10] RUN apt update                                                                                                          0.0s
=> CACHED [ 4/10] RUN apt install -y curl xz-utils python3 build-essential                                                                0.0s
=> CACHED [ 5/10] RUN corepack enable                                                                                                     0.0s
=> CACHED [ 6/10] RUN corepack prepare pnpm@7.25.1 --activate                                                                             0.0s
=> CACHED [ 7/10] COPY pnpm-lock.yaml ./ …
```
> chore: update pnpm version for signatures app in docker file

- packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx
- fixes #517 
- following the generation of payment pointer keys, we will now display the private key within a container, allowing the user to both copy it and  have it downloaded automatically;
> feat(wallet/frontend): display private key after generation

- packages/wallet/backend/package.json
- packages/wallet/backend/src/app.ts
- packages/wallet/backend/src/middleware/rateLimit.ts
- pnpm-lock.yaml
- fixes #537
- limit successful signup requests to 2 per 5 minutes on production (disabled on dev)
> feat: set rate limit on signup

- packages/wallet/backend/src/quote/service.ts
- packages/wallet/backend/src/rafiki/controller.ts
- packages/wallet/backend/src/rafiki/rafiki-client.ts
- packages/wallet/backend/src/rafiki/service.ts
-closes #501 
Rafiki now only fires the incoming_payment.expired Webhook if an incoming payment expires WITH money already sent in it.
Testnet makes use of this.
When we SEND TO AN EXISTING INCOMING PAYMENT, the flow is normal, and rafiki sends incoming_payment.completed.
When we SEND DIRECTLY TO PAYMENT POINTER, testnet backend automatically creates an incoming payment.
Note: the automatically created incoming payment **can either have an amount or not**. Depending on the send type:
- **FIXED SEND (send)**: we do not know the amount that the incoming payment should have beforehand, and as such we set the amount as null. The receiver can receive any amount.
As such, that incoming payment does not complete, since it does not get fulfilled.
But if we set the expiry as 15 seconds, and the …
> feat(backend): Slow incoming payments

- packages/wallet/backend/src/rafiki/rafiki-client.ts
- packages/wallet/backend/src/rafiki/service.ts
- fixes #709 
- return the invalid amount to rafiki so it will throw an `invalid amount` error itself instead of a generic one
- transform invalid amount error to a more user friendly message
This can be improved if rafiki will allow the client to throw errors that it can handle and return an equivalent message.
> fix(quote): change invalid amount error

- packages/commerce/backend/src/app.ts
- packages/commerce/backend/src/open-payments/service.ts
- packages/commerce/backend/src/order/controller.ts
- packages/commerce/backend/src/order/validation.ts
- packages/commerce/frontend/package.json
- packages/commerce/frontend/src/app/cart/components/summary.tsx
- packages/commerce/frontend/src/app/cart/index.tsx
- packages/commerce/frontend/src/app/checkout/components/order-summary.tsx
- packages/commerce/frontend/src/app/checkout/components/pay-button.tsx
- packages/commerce/frontend/src/app/checkout/components/payment-methods.tsx
- packages/commerce/frontend/src/app/checkout/index.tsx
- packages/commerce/frontend/src/app/checkout/routes.tsx
- packages/commerce/frontend/src/app/index.tsx
- packages/commerce/frontend/src/app/products/components/product-card.tsx
- packages/commerce/frontend/src/components/icons.tsx
- packages/commerce/frontend/src/components/ui/form/form.tsx
- packages/commerce/frontend/src/components/ui/input.tsx
- packages/commerce/frontend/src/components/ui/tabs.tsx
- packages/commerce/frontend/src/hooks/use-create-order-mutation.ts
- packages/commerce/frontend/src/hooks/use-custom-mutation.ts
- packages/commerce/frontend/src/hooks/use-product-query.ts
- packages/commerce/frontend/src/hooks/use-products-query.ts
- packages/commerce/frontend/src/lib/fetcher.ts
- packages/commerce/frontend/src/lib/utils.ts
- pnpm-lock.yaml
> feat(commerce/frontend): add checkout view

- README.md
I fixed the issue #829 that was assigned to me.
I have made the image in the readme.md liked with the heading of the file.
Earlier when we clicked on the picture, we were brought to a new tab with just the picture on it.
Now its fixed.
This is the [issue](https://github.com/interledger/testnet/issues/829)
> chore: Update documentation with linked image

- packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx
- packages/wallet/frontend/src/ui/CopyButton.tsx
- fixes #867 
Change Copy Private button, to copy private button as base 64 encoded string.
> feat(wallet-frontend): private key copy as base 64

- packages/wallet/frontend/src/components/settings/DeveloperKeys.tsx
- fixes #891 
Changed the classname from `overflow-hidden` to `overflow-scroll px-2`
> fix(wallet-frontend): overflow in developer keys page

- packages/boutique/backend/package.json
- pnpm-lock.yaml
https://github.com/interledger/open-payments/issues/378
`@interledger/open-payments@6.1.1` fixes the `useHttp` issue. We were not able to use the SDK in a local environment.
> fix(deps): bump `@interledger/open-payments` to `6.1.1`

- packages/wallet/frontend/src/components/dialogs/CreateWalletAddressDialog.tsx
- packages/wallet/frontend/src/pages/account/[accountId].tsx
- fixes #1059 
Added a new button on the Account Web monetization tab  payment pointer list, in order to create a WM PP directly from there as well, and not have to go back to the priginal PP list.
> feat(wallet-frontend): add create WM PP button to Web Monetization PP list

- packages/wallet/frontend/src/pages/auth/login.tsx
- fixes https://github.com/interledger/testnet/issues/1136
Added an invalid URL check before the callback URL redirection
> fix: added valid url check in callback url redirection

- packages/wallet/frontend/src/components/icons/Info.tsx
- packages/wallet/frontend/src/styles/main.css
- packages/wallet/frontend/src/ui/TogglePayment.tsx
- fixes #1319 
- added a tooltip for the send/receive toggle, the text is the same as in the oboarding
> fix: add tooltip to send receive

- packages/wallet/frontend/src/components/GrantDetails.tsx
- packages/wallet/frontend/src/pages/grants/index.tsx
> fix: Update Grant Badges

- .github/workflows/build-publish.yaml
This PR implies having a fixed value for pnpm version
This came up after a discussion on a [feature PR](https://github.com/interledger/testnet/pull/1355#discussion_r1616867057):
Having pnpm version at latest would force feature PR's to also either update pnpm themselves, or to merge pnpm update beforehand.
I suggest we do the pnpm updates manually, preferably at the same time with upgrading Rafiki, keeping our version on par with the one used in that codebase.
> chore: fixed pnpm version

- packages/wallet/frontend/src/lib/api/card.ts
- packages/wallet/frontend/src/pages/card/index.tsx
- Part of #1506
- Adds initial card service for the wallet frontend
- Adds a mock service that simulates a successful API call
> [!NOTE]
> **Not the final state of the service!**
>
> This is introduced so we can prototype faster on the frontend by simulating API calls to the backend. Once the wallet endpoints are added (all or one by one, the card service will have to be updated).
> feat(wallet/frontend): add temporary card service

- packages/wallet/backend/src/account/service.ts
- packages/wallet/backend/src/gatehub/client.ts
We were receiving `403` when trying to fetch the account balance.
- Updates `getWalletBalance` method to accept the managed user ID as well.
- Retrieve GH user ID from database when calling `accountService.list` and pass it to `getWalletBalance`
> fix(wallet/backend): send managed user id when retrieving wallet balance

- packages/wallet/frontend/src/middleware.ts
- packages/wallet/frontend/src/pages/kyc.tsx
- Closes #1700
- Redirects the user to homepage after kyc is complete (complete, not approved). In case the user still needs KYC, the user will be redirected back to the KYC page.
- Updates wallet frontend middleware - removed two step KYC (personal + proof)
> fix(wallet/frontend): redirect user to home page after KYC complete

- packages/boutique/frontend/src/components/theme-provider.tsx
change default of dark theme to light theme for test deployment,
since imageDark is used as imageUrl in productCards, but no imageDark is in backend response atm
> feat(boutique-frontend): change default of dark theme to light theme

- packages/shared/backend/src/model.ts
- packages/wallet/backend/src/card/service.ts
- packages/wallet/backend/src/gatehub/client.ts
- packages/wallet/backend/src/transaction/service.ts
> feat: save card transactions

- packages/boutique/frontend/src/components/ui/tabs.tsx
> fix: Update payment methods boutique

- packages/wallet/backend/src/backfillTrxDetails.ts
> fix: catch errors on backfill

- packages/wallet/frontend/src/middleware.ts
- packages/wallet/frontend/src/pages/auth/login.tsx
- packages/wallet/frontend/src/ui/ButtonOrLink.tsx
- fixes #1902 
The callback url will be stored in session storage until it is used by the login flow.
If the callback url provided does not exits the flow will redirect to '/'.
The redirect now works if the user is already logged in.
NONE: 
The callback url will not be retired as a param in the URL if the user navigate to "forgot password".
> fix: 1902 callback url is not preserved

- .github/workflows/build-publish.yaml
This pr fixes the url used for api_base_url in the jopacc-specific boutique frontend image
> fix(build&publish): correct API base URLs in build-publish workflow

- packages/wallet/frontend/src/components/dialogs/TransactionDetailsDialog.tsx
- packages/wallet/frontend/src/components/providers/RefundProvider.tsx
- packages/wallet/frontend/src/components/providers/index.tsx
- packages/wallet/frontend/src/lib/context/refund.ts
- packages/wallet/frontend/src/pages/send.tsx
- fixes #1929 
When second party Wallet Address is available, show it on Transaction Details popup.
Also add a button to redirect to send page, with the second party WA already pre-populated. This is a kind of a refund when you receive money, or it is a Send Again functionality when you sent someone money and you want to send again.
> feat: Add second party WA, and refund option

- packages/wallet/frontend/src/lib/hooks/useToast.ts
- packages/wallet/frontend/src/pages/_app.tsx
- fixes #1907 
When you are on transaction page, and toast notification appears with you receiving money, reload the transaction page, to see the Completed status of the transaction.
> feat: Reload transaction page when money is received
